const{test,expect} = require('@playwright/test')
const RegistrationFormPage = require("../pages/RegistraionFormPage")
const TransactionDetailsPage = require('../pages/TransactionDetailsPage')
const testdata = require("../registerform.json")
const transactionTestdata = require("../transactiondetails.json")

test("Register the form", async({page}) => {
    await page.goto(testdata.baseUrl)
    const registrationFormPage = new RegistrationFormPage(page)
    await registrationFormPage.enterFirstname(testdata.firstname)
    await registrationFormPage.verifyFirstName(testdata.firstname)
    await registrationFormPage.enterLastName(testdata.lastname)
    await registrationFormPage.verifyLastName(testdata.lastname)
    await registrationFormPage.selectMaleGender()
    await registrationFormPage.verifyGenderSelectionOption()
    await registrationFormPage.enterAddress(testdata.Address)
    await registrationFormPage.verifyAddress(testdata.Address)
    await registrationFormPage.enterCity(testdata.city)
    await registrationFormPage.verifyCity(testdata.city)
    await registrationFormPage.enterState(testdata.state)
    await registrationFormPage.verifyState(testdata.state)
    await registrationFormPage.enterPostalCode(testdata.postalcode)
    await registrationFormPage.verifyPostalCode(testdata.postalcode)
    await registrationFormPage.selectCountry(testdata.country)
    await registrationFormPage.verifyCountry(testdata.country)
    await registrationFormPage.enterEmail(testdata.email)
    await registrationFormPage.verifyEmail(testdata.email)
    await registrationFormPage.enterDateOfDemo(testdata.dateofdemo)
    await registrationFormPage.verifyDateOfDemo(testdata.dateofdemo)
    await registrationFormPage.selectConvenientTime(testdata.hour, testdata.minute)
    await registrationFormPage.verifyConvenientTime(testdata.hour, testdata.minute)
    await registrationFormPage.enterMobile(testdata.mobile)
    await registrationFormPage.verifyMobile(testdata.mobile)
    await registrationFormPage.selectCourse()
    await registrationFormPage.verifyCourseSelection()
    await registrationFormPage.enterYourQuery(testdata.query)
    await registrationFormPage.verifyYourQuery(testdata.query)
    await registrationFormPage.enterVerificationCode(testdata.verificationCode)
    await registrationFormPage.verifyVerificationCode(testdata.verificationCode)
    await registrationFormPage.clickOnSubmitButton()

    const transactionDetailsPage =new TransactionDetailsPage(page)
    await transactionDetailsPage.verifyTransactionPageURL(transactionTestdata.transactionUrl)
    await transactionDetailsPage.verifyTranactionPageTitle(transactionTestdata.transactionTitle)
    await transactionDetailsPage.verifySuccessMessage(transactionTestdata.success)
})
